# Generated by Django 5.0 on 2024-01-08 18:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of food category, must be unique.', max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of ingredient. Should be either 'descriptor item' or 'item, descriptor'", max_length=100, unique=True, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Ingredient')),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='recipes_ing_name_164c6a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('main_ingredient', models.CharField(choices=[('BEEF', 'Beef'), ('CHICKEN', 'Chicken'), ('PORK', 'Pork'), ('EGGS', 'Eggs'), ('VEGETABLE', 'Vegetable'), ('DAIRY', 'Dairy'), ('GRAINS', 'Grains'), ('LEGUMES', 'Legumes'), ('SUGAR', 'Sugary Sweet')], default='VEGETABLE', max_length=9)),
                ('categories', models.ManyToManyField(to='recipes.category')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity is used in combination with measure and ingredient to form a recipe ingredient.', max_digits=6)),
                ('measure', models.CharField(choices=[('pinch', 'pinch'), ('tsp', 'teaspoon'), ('tbsp', 'tablespoon'), ('c', 'cup'), ('pt', 'pint'), ('qt', 'quart'), ('gal', 'gallon'), ('oz', 'ounce'), ('l', 'liter'), ('ml', 'milliliter'), ('g', 'gram'), ('kg', 'kilogram'), ('none', ' ')], default='none', max_length=6)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipes.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipes.recipe')),
            ],
        ),
    ]
