# Generated by Django 5.0 on 2024-01-07 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='main_focus',
            field=models.CharField(choices=[('BEEF', 'Beef'), ('CHICKEN', 'Chicken'), ('PORK', 'Pork'), ('EGGS', 'Eggs'), ('VEGETABLE', 'Vegetable'), ('DAIRY', 'Dairy'), ('GRAINS', 'Grains'), ('LEGUMES', 'Legumes')], default='VEGETABLE', max_length=9),
        ),
    ]
