# Generated by Django 5.0 on 2024-01-18 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('APPETIZERS', 'Appetizers'), ('BREAD', 'Bread'), ('BREAKFAST', 'Breakfast'), ('CAKE', 'Cakes'), ('COOKIES', 'Cookies'), ('CURRIES', 'Curries'), ('DRINKS', 'Drinks'), ('FERMENTS', 'Ferments'), ('MAIN', 'Main'), ('NOODLES', 'Noodles'), ('PANTRY', 'Pantry'), ('PASTRY', 'Pastry'), ('PIES', 'Pies'), ('RICE', 'Rice'), ('SIDE', 'Side'), ('SALAD', 'Salad'), ('SANDWICHES', 'Sandwiches'), ('SAUCES', 'Sauces'), ('SPICE', 'Spice Blend'), ('TARTS', 'Tarts')], default='BREAD', max_length=10),
        ),
    ]
