# Generated by Django 5.0 on 2024-01-07 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_main_focus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='main_focus',
            field=models.CharField(choices=[('BEEF', 'Beef'), ('CHICKEN', 'Chicken'), ('PORK', 'Pork'), ('EGGS', 'Eggs'), ('VEGETABLE', 'Vegetable'), ('DAIRY', 'Dairy'), ('GRAINS', 'Grains'), ('LEGUMES', 'Legumes'), ('SUGAR', 'Sugary Sweet')], default='VEGETABLE', max_length=9),
        ),
    ]
